# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(131416)
$foreground = rgb(CEE2DC)
$color0 = rgb(3D3E41)
$color1 = rgb(454F59)
$color2 = rgb(A54148)
$color3 = rgb(417A86)
$color4 = rgb(40808C)
$color5 = rgb(B39786)
$color6 = rgb(74AC9B)
$color7 = rgb(B1CDC5)
$color8 = rgb(7C908A)
$color9 = rgb(454F59)
$color10 = rgb(A54148)
$color11 = rgb(417A86)
$color12 = rgb(40808C)
$color13 = rgb(B39786)
$color14 = rgb(74AC9B)
$color15 = rgb(B1CDC5)
