vim.g.mapleader = " "
vim.cmd("cabbrev W w")
vim.keymap.set("v", "x", '"_x')
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("n", "<leader><leader>", "<cmd>source %<CR>")
vim.keymap.set("v", "<leader>d", '"_d')
vim.keymap.set("x", "<leader>p", [["_dP]])
vim.keymap.set("i", "<C-c>", "<Esc>")
vim.keymap.set("n", "<leader>d", '"_d')
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("n", "<leader>cf", function()
	local conform = require("conform")
	conform.format({
		timeout_ms = 5000,
		lsp_fallback = true,
	})
end)
vim.keymap.set("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]], { desc = "replace work under cursor" })
vim.keymap.set("n", "x", '"_x')
vim.keymap.set("n", "<C-f>", "<C-b>")
vim.keymap.set("n", "<C-b>", "<C-f>")
vim.keymap.set("n", "<leader>nh", ":nohl<CR>", { desc = "Clear search highlights" })
vim.keymap.set("n", "<leader>sv", "<C-w>v", { desc = "Split window vertically" })
vim.keymap.set("n", "<leader>sx", "<cmd>close<CR>", { desc = "Close current split" })
vim.keymap.set("n", "<C-minus>", "<C-w><", { desc = "Decrease split width" })
vim.keymap.set("n", "<C-=>", "<C-w>>", { desc = "Increase split width" })
vim.keymap.set("n", "<leader>to", "<cmd>tabnew<CR>", { desc = "Open new tab" })
vim.keymap.set("n", "<leader>tx", "<cmd>tabclose<CR>", { desc = "Close current tab" })
vim.keymap.set("n", "<leader>sh", "<C-w>s", { desc = "Split window horizontally" })
vim.keymap.set("n", "<leader>se", "<C-w>=", { desc = "Make splits equal size" })
vim.keymap.set("n", "<leader>tn", "<cmd>tabn<CR>", { desc = "Go to next tab" })
vim.keymap.set("n", "<leader>tp", "<cmd>tabp<CR>", { desc = "Go to previous tab" })
vim.keymap.set("n", "<leader>tf", "<cmd>tabnew %<CR>", { desc = "Open current buffer in new tab" })
vim.keymap.set("n", "<C-h>", "<C-w>h")
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "<leader>m", "@")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
