-- Generated by HyprMod (converted to Lua)

hl.config({
    cursor = {
        inactive_timeout = 1,
        no_warps = 0,
    },
    general = {
        resize_on_border = true,
    }
})

hl.monitor({
    output = "eDP-1",
    mode = "1366x768@60.02Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
