# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DDEBE2
background         #101010
cursor             #B5998D

active_tab_foreground     #101010
active_tab_background     #DDEBE2
inactive_tab_foreground   #DDEBE2
inactive_tab_background   #101010

active_border_color   #DDEBE2
inactive_border_color #101010
bell_border_color     #484848

color0      #3B3B3A
color1		#484848
color2		#A67066
color3		#728275
color4		#668371
color5		#668371
color6		#9FC7AC
color7		#C7DBCD
color8		#8B9990
color9		#484848
color10		#A67066
color11		#728275
color12		#668371
color13		#668371
color14		#9FC7AC
color15		#C7DBCD